baseURL = ""
title = "Hugo Theme Pack"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "lander"
pygmentsUseClasses = true

[params]
  [params.footer]
    title = "About"
    text = """
    Hugo Theme Pack is project boilerplate for building Hugo themes with Webpack.
    """
  [params.seo]
    category = "Hugo Theme"
    downloadURL = "#"
    versionEnv = "npm_package_version"
    operatingSystem = "Any"
    isFree = true
    license = "#"
    defaultAuthor = "Hugo Theme Pack Contributors"
  [params.colors]
    primary-600 = "hsl(240, 30%, 51%)"
    primary-500 = "hsl(240, 30%, 54%)"
    primary-400 = "hsl(240, 30%, 59%)"
    accent-600 = "hsl(350, 60%, 43%)"
    accent-500 = "hsl(350, 60%, 46%)"
    accent-400 = "hsl(350, 60%, 50%)"
    background-900 = "hsl(340, 15%, 86%)"
    background-200 = "hsl(340, 15%, 82%)"
    background-100 = "hsl(340, 14%, 92%)"
    text-900 = "hsla(0, 0%, 0%, 0.75)"
    text-800 = "hsla(0, 0%, 0%, 0.7)"
    text-700 = "hsla(0, 0%, 0%, 0.65)"
    text-200 = "hsla(0, 0%, 100%, 0.85)"
    text-100 = "hsla(0, 0%, 0%, 0.7)"
    highlight-text = "hsl(240, 35%, 99%)"
    highlight-background = "hsl(240, 13%, 14%)"
    highlight-comment = "hsl(250, 25%, 55%)"
    highlight-special = "hsl(180, 75%, 55%)"
    highlight-operator = "hsl(330, 95%, 75%)"
    highlight-literal = "hsl(250, 80%, 70%)"

[taxonomies]
category = "categories"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
