baseURL = "https://lkummer.github.io/Satelite/demo/"
title = "Satelite Demo"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

pygmentsUseClasses = true
theme = "satelite"

taxonomies = []

[outputs]
  home = ["HTML", "JSON"]

[menu]
[[menu.main]]
  name = "Documentation"
  url = "https://lkummer.github.io/Satelite"
  weight = -20
[[menu.main]]
  name = "Github"
  url = "https://github.com/LKummer/Satelite"

[params]
[params.seo]
  description = "Satelite Hugo theme demo."
[params.icons]
  favicon = "images/favicon.svg"
  navbarIcon = """
    <svg class="navbar-logo-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
      viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
      <style type="text/css">
        .logo-satelite {
          fill: #CDC8E6;
          transform-origin: 32px 32px;
          transform: rotate(calc(var(--logo-hover) * 360deg));
          transition: transform 1s;
        }
        .logo-planet {
          fill: #CDC8E6;
        }
        .logo-planet-shade {
          fill: #A69FD1;
        }
      </style>
      <path class="logo-satelite" d="M59.8,21.6c-0.1,0.1-0.2,0.1-0.3,0.2c-0.3,0.2-0.5,0.3-0.8,0.4c-1.8,0.6-3.9-0.2-4.9-1.9
        c-1-1.7-0.6-3.9,0.8-5.2C46,3.9,30.2,0.6,17.6,7.9C5,15.1,0,30.4,5.3,43.5c0.5,1.2,1.1,2.5,1.8,3.7c0.2,0.3,0.1,0.6-0.2,0.8
        c-0.3,0.2-0.6,0.1-0.8-0.2c-0.7-1.2-1.3-2.5-1.8-3.8C-1.3,30.4,3.9,14.4,17,6.8s29.6-4.1,38.6,7.5c2-1,4.3-0.2,5.5,1.7
        C62.2,17.9,61.6,20.3,59.8,21.6z"/>
      <circle class="logo-planet" cx="32" cy="32.8" r="20.4"/>
      <path class="logo-planet-shade" d="M52.4,32.8c0,11.3-9.1,20.4-20.4,20.4c-3.5,0-6.7-0.9-9.5-2.4c-1.5-2.8-2.4-6.1-2.4-9.5
        c0-11.3,9.1-20.4,20.4-20.4c3.4,0,6.7,0.9,9.5,2.4C51.5,26.1,52.4,29.3,52.4,32.8z"/>
    </svg>
    """
