baseURL = "https://gohugo.io"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[menu]

  [[menu.main]]
    title = "Github"
    permalink = "https://github.com/LKummer"

theme = "hugo-theme-boilerplate"
